version: "3"
services:
  react-app:
    container_name: jizo_landing_react
    build:
      context: ./
      dockerfile: ./docker/react/Dockerfile
    image: react
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - jizo_landing_node_modules:/app/node_modules
    environment:
     CHOKIDAR_USEPOLLING: "true"
    networks:
      - jizo_landing
  storybook:
    build:
      context: ./
      dockerfile: ./docker/storybook/Dockerfile
    image: storybook
    container_name: jizo_landing_storybook
    ports:
      - "8086:6006"
    volumes:
      - .:/usr/src/app
    networks:
      - jizo_landing

networks:
  jizo_landing:
    driver: bridge
volumes:
  jizo_landing_node_modules: