version: "3"
services:
  react-app:
    container_name: jizo_landing_react
    build:
      context: ./
      dockerfile: ./docker/react/Dockerfile
    image: react
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - jizo-landing
  storybook:
    build:
      context: ./
      dockerfile: ./docker/storybook/Dockerfile
    image: storybook
    container_name: jizo_landing_storybook
    ports:
      - "8086:6006"
    volumes:
      - ./app:/usr/src/app
    networks:
      - jizo-landing

networks:
  jizo-landing:
    driver: bridge