version: "3"
services:
  react-app:
    container_name: jizo_landing_react
    build:
      context: ./
      dockerfile: ./docker/react/Dockerfile
    image: react
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - jizo_landing_node_modules:/app/node_modules
    environment:
     CHOKIDAR_USEPOLLING: "true"
    networks:
      - jizo_landing
  storybook:
    build:
      context: ./
      dockerfile: ./docker/storybook/Dockerfile
    image: storybook
    container_name: jizo_landing_storybook
    ports:
      - "8086:6006"
    volumes:
      - .:/usr/src/app
    networks:
      - jizo_landing
  mailer:
    image: "ghcr.io/docker-mailserver/docker-mailserver:latest"
    container_name: mailer
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: jizo@contact.fr
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always

networks:
  jizo_landing:
    driver: bridge
volumes:
  jizo_landing_node_modules: